apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  request: {your .csr file contents}
 signerName: kubernetes.io/kube-apiserver-client
 expirationSeconds: 86400
 usages:
   - client auth
