apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  namespace: default
  labels:
    app: static-busybox
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "1000"]
