apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1000
#preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for low-priority application pods."
