apiVersion: v1
kind: Pod
metadata:
  name: orange
  labels:
    app: orange
spec:
  containers:
  - name: orange-container
    image: busybox:1.28
  initContainers:
  - name: init-myservice
    image: busybox
    restartPolicy: Always
    command: ['sleep', '20']
