apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: kodekloud/event-simulator
    volumeMounts:
    - name: webapp-logs
      mountPath: /log  # Your specified volume mount
  volumes:
  - name: webapp-logs
    hostPath:
      path: /var/log/webapp # Your specified host path
      type: DirectoryOrCreate
