apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: kodekloud/event-simulator
    volumeMounts:
    - name: webapp-pvc-storage
      mountPath: /log
  volumes:
  - name: webapp-pvc-storage
    persistentVolumeClaim:
      claimName: claim-log-1
