apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_Host: c3FsMDE= # base64 encoded "sql01"
  DB_User: cm9vdA==   # base64 encoded "root"
  DB_Password: cGFzc3dvcmQxMjM= # base64 encoded "password123"
